version: "3.7"
services:
  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    image: opensearchproject/data-prepper:2
    volumes:
      - ./trace_analytics_no_ssl_2x.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    ports:
      - "21890:21890"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:21890/health"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  otel-collector:
    restart: unless-stopped
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.64.1
    command: [ "--config=/etc/otel-collector-config.yml" ]
    working_dir: "/project"
    volumes:
      - ${PWD}/:/project
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "14250:14250"
      - "13133:13133"
      - "55677:55677"
      - "55678:55678"
      - "55679:55679"
    depends_on:
      data-prepper:
        condition: service_healthy

  jaeger-agent:
    container_name: jaeger-agent
    image: jaegertracing/jaeger-agent:latest
    command: [ "--reporter.grpc.host-port=otel-collector:14250" ]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
    depends_on:
      - otel-collector

  # jaeger-hot-rod:
  #   image: jaegertracing/example-hotrod:1.41.0
  #   command: [ "all" ]
  #   environment:
  #     - JAEGER_AGENT_HOST=jaeger-agent
  #     - JAEGER_AGENT_PORT=6831
  #   ports:
  #     - "8080-8083:8080-8083"
  #   depends_on:
  #     - jaeger-agent
