global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).



scrape_configs:
  - job_name: otel_collector
    static_configs:
    - targets: ['otel_collector:8889'] # using the name of the OpenTelemetryCollector container defined in the docker compose file
  # - job_name: 'otel_collector'
  #   scrape_interval: 5s
  #   static_configs:
  #        - targets: ['otel_collector:5778']
  # - job_name: 'jaeger-ingester'
  #   scrape_interval: 5s
  #   static_configs:
  #        - targets: ['jaeger-ingester:14271']
  # - job_name: 'otel_collector'
  #   scrape_interval: 5s
  #   static_configs:
  #        - targets: ['otel_collector:14268']
  # - job_name: 'otel_collector'
  #   scrape_interval: 5s
  #   static_configs:
  #        - targets: ['otel_collector:16686']