receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

  otlp:
    protocols:
      http:
        include_metadata: true
        cors:
          allowed_origins:
            - http://localhost:3000/
            - http://localhost:3000
          allowed_headers:
            - "*"
          max_age: 7200

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

connectors:
  spanmetrics:

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [spanmetrics, jaeger]

    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]